// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Grafana.OpenApiClient.AccessControl.Item;
using Soenneker.Grafana.OpenApiClient.AccessControl.Roles;
using Soenneker.Grafana.OpenApiClient.AccessControl.Status;
using Soenneker.Grafana.OpenApiClient.AccessControl.Teams;
using Soenneker.Grafana.OpenApiClient.AccessControl.Users;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Grafana.OpenApiClient.AccessControl
{
    /// <summary>
    /// Builds and executes requests for operations under \access-control
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AccessControlRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The roles property</summary>
        public global::Soenneker.Grafana.OpenApiClient.AccessControl.Roles.RolesRequestBuilder Roles
        {
            get => new global::Soenneker.Grafana.OpenApiClient.AccessControl.Roles.RolesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The status property</summary>
        public global::Soenneker.Grafana.OpenApiClient.AccessControl.Status.StatusRequestBuilder Status
        {
            get => new global::Soenneker.Grafana.OpenApiClient.AccessControl.Status.StatusRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The teams property</summary>
        public global::Soenneker.Grafana.OpenApiClient.AccessControl.Teams.TeamsRequestBuilder Teams
        {
            get => new global::Soenneker.Grafana.OpenApiClient.AccessControl.Teams.TeamsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The users property</summary>
        public global::Soenneker.Grafana.OpenApiClient.AccessControl.Users.UsersRequestBuilder Users
        {
            get => new global::Soenneker.Grafana.OpenApiClient.AccessControl.Users.UsersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Soenneker.Grafana.OpenApiClient.accessControl.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Soenneker.Grafana.OpenApiClient.AccessControl.Item.WithResourceItemRequestBuilder"/></returns>
        public global::Soenneker.Grafana.OpenApiClient.AccessControl.Item.WithResourceItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("resource", position);
                return new global::Soenneker.Grafana.OpenApiClient.AccessControl.Item.WithResourceItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Grafana.OpenApiClient.AccessControl.AccessControlRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AccessControlRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/access-control", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Grafana.OpenApiClient.AccessControl.AccessControlRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AccessControlRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/access-control", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
