// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Grafana.OpenApiClient.ConvertNamespace.Api;
using Soenneker.Grafana.OpenApiClient.ConvertNamespace.Prometheus;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Grafana.OpenApiClient.ConvertNamespace
{
    /// <summary>
    /// Builds and executes requests for operations under \convert
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ConvertRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The api property</summary>
        public global::Soenneker.Grafana.OpenApiClient.ConvertNamespace.Api.ApiRequestBuilder Api
        {
            get => new global::Soenneker.Grafana.OpenApiClient.ConvertNamespace.Api.ApiRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The prometheus property</summary>
        public global::Soenneker.Grafana.OpenApiClient.ConvertNamespace.Prometheus.PrometheusRequestBuilder Prometheus
        {
            get => new global::Soenneker.Grafana.OpenApiClient.ConvertNamespace.Prometheus.PrometheusRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Grafana.OpenApiClient.ConvertNamespace.ConvertRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ConvertRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/convert", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Grafana.OpenApiClient.ConvertNamespace.ConvertRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ConvertRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/convert", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
