// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Grafana.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AlertRuleNotificationSettingsExport : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The active_time_intervals property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ActiveTimeIntervals { get; set; }
#nullable restore
#else
        public List<string> ActiveTimeIntervals { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The group_by property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? GroupBy { get; set; }
#nullable restore
#else
        public List<string> GroupBy { get; set; }
#endif
        /// <summary>The group_interval property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GroupInterval { get; set; }
#nullable restore
#else
        public string GroupInterval { get; set; }
#endif
        /// <summary>The group_wait property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GroupWait { get; set; }
#nullable restore
#else
        public string GroupWait { get; set; }
#endif
        /// <summary>The mute_time_intervals property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? MuteTimeIntervals { get; set; }
#nullable restore
#else
        public List<string> MuteTimeIntervals { get; set; }
#endif
        /// <summary>The receiver property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Receiver { get; set; }
#nullable restore
#else
        public string Receiver { get; set; }
#endif
        /// <summary>The repeat_interval property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RepeatInterval { get; set; }
#nullable restore
#else
        public string RepeatInterval { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Grafana.OpenApiClient.Models.AlertRuleNotificationSettingsExport"/> and sets the default values.
        /// </summary>
        public AlertRuleNotificationSettingsExport()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Grafana.OpenApiClient.Models.AlertRuleNotificationSettingsExport"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Grafana.OpenApiClient.Models.AlertRuleNotificationSettingsExport CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Grafana.OpenApiClient.Models.AlertRuleNotificationSettingsExport();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "active_time_intervals", n => { ActiveTimeIntervals = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "group_by", n => { GroupBy = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "group_interval", n => { GroupInterval = n.GetStringValue(); } },
                { "group_wait", n => { GroupWait = n.GetStringValue(); } },
                { "mute_time_intervals", n => { MuteTimeIntervals = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "receiver", n => { Receiver = n.GetStringValue(); } },
                { "repeat_interval", n => { RepeatInterval = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("active_time_intervals", ActiveTimeIntervals);
            writer.WriteCollectionOfPrimitiveValues<string>("group_by", GroupBy);
            writer.WriteStringValue("group_interval", GroupInterval);
            writer.WriteStringValue("group_wait", GroupWait);
            writer.WriteCollectionOfPrimitiveValues<string>("mute_time_intervals", MuteTimeIntervals);
            writer.WriteStringValue("receiver", Receiver);
            writer.WriteStringValue("repeat_interval", RepeatInterval);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
