// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Grafana.OpenApiClient.Models
{
    /// <summary>
    /// TODO docsFROM: AnnotationQuery in grafana-data/src/types/annotations.ts
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AnnotationQuery : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Set to 1 for the standard annotation query all dashboards have by default.</summary>
        public double? BuiltIn { get; set; }
        /// <summary>Ref to a DataSource instance</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Grafana.OpenApiClient.Models.DataSourceRef? Datasource { get; set; }
#nullable restore
#else
        public global::Soenneker.Grafana.OpenApiClient.Models.DataSourceRef Datasource { get; set; }
#endif
        /// <summary>When enabled the annotation query is issued with every dashboard refresh</summary>
        public bool? Enable { get; set; }
        /// <summary>The filter property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Grafana.OpenApiClient.Models.AnnotationPanelFilter? Filter { get; set; }
#nullable restore
#else
        public global::Soenneker.Grafana.OpenApiClient.Models.AnnotationPanelFilter Filter { get; set; }
#endif
        /// <summary>Annotation queries can be toggled on or off at the top of the dashboard.When hide is true, the toggle is not shown in the dashboard.</summary>
        public bool? Hide { get; set; }
        /// <summary>Color to use for the annotation event markers</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IconColor { get; set; }
#nullable restore
#else
        public string IconColor { get; set; }
#endif
        /// <summary>Name of annotation.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Placement can be used to display the annotation query somewhere else on the dashboard other than the default location.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Placement { get; set; }
#nullable restore
#else
        public string Placement { get; set; }
#endif
        /// <summary>TODO: this should be a regular DataQuery that depends on the selected dashboardthese match the properties of the &quot;grafana&quot; datasouce that is default in most dashboards</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Grafana.OpenApiClient.Models.AnnotationTarget? Target { get; set; }
#nullable restore
#else
        public global::Soenneker.Grafana.OpenApiClient.Models.AnnotationTarget Target { get; set; }
#endif
        /// <summary>TODO -- this should not exist here, it is based on the --grafana-- datasource</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Grafana.OpenApiClient.Models.AnnotationQuery"/> and sets the default values.
        /// </summary>
        public AnnotationQuery()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Grafana.OpenApiClient.Models.AnnotationQuery"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Grafana.OpenApiClient.Models.AnnotationQuery CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Grafana.OpenApiClient.Models.AnnotationQuery();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "builtIn", n => { BuiltIn = n.GetDoubleValue(); } },
                { "datasource", n => { Datasource = n.GetObjectValue<global::Soenneker.Grafana.OpenApiClient.Models.DataSourceRef>(global::Soenneker.Grafana.OpenApiClient.Models.DataSourceRef.CreateFromDiscriminatorValue); } },
                { "enable", n => { Enable = n.GetBoolValue(); } },
                { "filter", n => { Filter = n.GetObjectValue<global::Soenneker.Grafana.OpenApiClient.Models.AnnotationPanelFilter>(global::Soenneker.Grafana.OpenApiClient.Models.AnnotationPanelFilter.CreateFromDiscriminatorValue); } },
                { "hide", n => { Hide = n.GetBoolValue(); } },
                { "iconColor", n => { IconColor = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "placement", n => { Placement = n.GetStringValue(); } },
                { "target", n => { Target = n.GetObjectValue<global::Soenneker.Grafana.OpenApiClient.Models.AnnotationTarget>(global::Soenneker.Grafana.OpenApiClient.Models.AnnotationTarget.CreateFromDiscriminatorValue); } },
                { "type", n => { Type = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("builtIn", BuiltIn);
            writer.WriteObjectValue<global::Soenneker.Grafana.OpenApiClient.Models.DataSourceRef>("datasource", Datasource);
            writer.WriteBoolValue("enable", Enable);
            writer.WriteObjectValue<global::Soenneker.Grafana.OpenApiClient.Models.AnnotationPanelFilter>("filter", Filter);
            writer.WriteBoolValue("hide", Hide);
            writer.WriteStringValue("iconColor", IconColor);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("placement", Placement);
            writer.WriteObjectValue<global::Soenneker.Grafana.OpenApiClient.Models.AnnotationTarget>("target", Target);
            writer.WriteStringValue("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
