// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Grafana.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Annotation : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The alertId property</summary>
        public long? AlertId { get; set; }
        /// <summary>The alertName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AlertName { get; set; }
#nullable restore
#else
        public string AlertName { get; set; }
#endif
        /// <summary>The avatarUrl property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AvatarUrl { get; set; }
#nullable restore
#else
        public string AvatarUrl { get; set; }
#endif
        /// <summary>The created property</summary>
        public long? Created { get; set; }
        /// <summary>Deprecated: Use DashboardUID and OrgID instead</summary>
        public long? DashboardId { get; set; }
        /// <summary>The dashboardUID property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DashboardUID { get; set; }
#nullable restore
#else
        public string DashboardUID { get; set; }
#endif
        /// <summary>The data property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Grafana.OpenApiClient.Models.Json? Data { get; set; }
#nullable restore
#else
        public global::Soenneker.Grafana.OpenApiClient.Models.Json Data { get; set; }
#endif
        /// <summary>The email property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Email { get; set; }
#nullable restore
#else
        public string Email { get; set; }
#endif
        /// <summary>The id property</summary>
        public long? Id { get; set; }
        /// <summary>The login property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Login { get; set; }
#nullable restore
#else
        public string Login { get; set; }
#endif
        /// <summary>The newState property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NewState { get; set; }
#nullable restore
#else
        public string NewState { get; set; }
#endif
        /// <summary>The panelId property</summary>
        public long? PanelId { get; set; }
        /// <summary>The prevState property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PrevState { get; set; }
#nullable restore
#else
        public string PrevState { get; set; }
#endif
        /// <summary>The tags property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Tags { get; set; }
#nullable restore
#else
        public List<string> Tags { get; set; }
#endif
        /// <summary>The text property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Text { get; set; }
#nullable restore
#else
        public string Text { get; set; }
#endif
        /// <summary>The time property</summary>
        public long? Time { get; set; }
        /// <summary>The timeEnd property</summary>
        public long? TimeEnd { get; set; }
        /// <summary>The updated property</summary>
        public long? Updated { get; set; }
        /// <summary>The userId property</summary>
        public long? UserId { get; set; }
        /// <summary>The userUID property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserUID { get; set; }
#nullable restore
#else
        public string UserUID { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Grafana.OpenApiClient.Models.Annotation"/> and sets the default values.
        /// </summary>
        public Annotation()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Grafana.OpenApiClient.Models.Annotation"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Grafana.OpenApiClient.Models.Annotation CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Grafana.OpenApiClient.Models.Annotation();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "alertId", n => { AlertId = n.GetLongValue(); } },
                { "alertName", n => { AlertName = n.GetStringValue(); } },
                { "avatarUrl", n => { AvatarUrl = n.GetStringValue(); } },
                { "created", n => { Created = n.GetLongValue(); } },
                { "dashboardId", n => { DashboardId = n.GetLongValue(); } },
                { "dashboardUID", n => { DashboardUID = n.GetStringValue(); } },
                { "data", n => { Data = n.GetObjectValue<global::Soenneker.Grafana.OpenApiClient.Models.Json>(global::Soenneker.Grafana.OpenApiClient.Models.Json.CreateFromDiscriminatorValue); } },
                { "email", n => { Email = n.GetStringValue(); } },
                { "id", n => { Id = n.GetLongValue(); } },
                { "login", n => { Login = n.GetStringValue(); } },
                { "newState", n => { NewState = n.GetStringValue(); } },
                { "panelId", n => { PanelId = n.GetLongValue(); } },
                { "prevState", n => { PrevState = n.GetStringValue(); } },
                { "tags", n => { Tags = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "text", n => { Text = n.GetStringValue(); } },
                { "time", n => { Time = n.GetLongValue(); } },
                { "timeEnd", n => { TimeEnd = n.GetLongValue(); } },
                { "updated", n => { Updated = n.GetLongValue(); } },
                { "userId", n => { UserId = n.GetLongValue(); } },
                { "userUID", n => { UserUID = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteLongValue("alertId", AlertId);
            writer.WriteStringValue("alertName", AlertName);
            writer.WriteStringValue("avatarUrl", AvatarUrl);
            writer.WriteLongValue("created", Created);
            writer.WriteLongValue("dashboardId", DashboardId);
            writer.WriteStringValue("dashboardUID", DashboardUID);
            writer.WriteObjectValue<global::Soenneker.Grafana.OpenApiClient.Models.Json>("data", Data);
            writer.WriteStringValue("email", Email);
            writer.WriteLongValue("id", Id);
            writer.WriteStringValue("login", Login);
            writer.WriteStringValue("newState", NewState);
            writer.WriteLongValue("panelId", PanelId);
            writer.WriteStringValue("prevState", PrevState);
            writer.WriteCollectionOfPrimitiveValues<string>("tags", Tags);
            writer.WriteStringValue("text", Text);
            writer.WriteLongValue("time", Time);
            writer.WriteLongValue("timeEnd", TimeEnd);
            writer.WriteLongValue("updated", Updated);
            writer.WriteLongValue("userId", UserId);
            writer.WriteStringValue("userUID", UserUID);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
