// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Grafana.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CacheConfigResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The created property</summary>
        public DateTimeOffset? Created { get; set; }
        /// <summary>Fields that can be set by the API caller - read/write</summary>
        public long? DataSourceID { get; set; }
        /// <summary>The dataSourceUID property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DataSourceUID { get; set; }
#nullable restore
#else
        public string DataSourceUID { get; set; }
#endif
        /// <summary>These are returned by the HTTP API, but are managed internally - read-onlyNote: &apos;created&apos; and &apos;updated&apos; are special properties managed automatically by xorm, but we are setting them manually</summary>
        public long? DefaultTTLMs { get; set; }
        /// <summary>The enabled property</summary>
        public bool? Enabled { get; set; }
        /// <summary>The message property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Message { get; set; }
#nullable restore
#else
        public string Message { get; set; }
#endif
        /// <summary>TTL MS, or &quot;time to live&quot;, is how long a cached item will stay in the cache before it is removed (in milliseconds)</summary>
        public long? TtlQueriesMs { get; set; }
        /// <summary>The ttlResourcesMs property</summary>
        public long? TtlResourcesMs { get; set; }
        /// <summary>The updated property</summary>
        public DateTimeOffset? Updated { get; set; }
        /// <summary>If UseDefaultTTL is enabled, then the TTLQueriesMS and TTLResourcesMS in this object is always sent as the default TTL located in grafana.ini</summary>
        public bool? UseDefaultTTL { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Grafana.OpenApiClient.Models.CacheConfigResponse"/> and sets the default values.
        /// </summary>
        public CacheConfigResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Grafana.OpenApiClient.Models.CacheConfigResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Grafana.OpenApiClient.Models.CacheConfigResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Grafana.OpenApiClient.Models.CacheConfigResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "created", n => { Created = n.GetDateTimeOffsetValue(); } },
                { "dataSourceID", n => { DataSourceID = n.GetLongValue(); } },
                { "dataSourceUID", n => { DataSourceUID = n.GetStringValue(); } },
                { "defaultTTLMs", n => { DefaultTTLMs = n.GetLongValue(); } },
                { "enabled", n => { Enabled = n.GetBoolValue(); } },
                { "message", n => { Message = n.GetStringValue(); } },
                { "ttlQueriesMs", n => { TtlQueriesMs = n.GetLongValue(); } },
                { "ttlResourcesMs", n => { TtlResourcesMs = n.GetLongValue(); } },
                { "updated", n => { Updated = n.GetDateTimeOffsetValue(); } },
                { "useDefaultTTL", n => { UseDefaultTTL = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("created", Created);
            writer.WriteLongValue("dataSourceID", DataSourceID);
            writer.WriteStringValue("dataSourceUID", DataSourceUID);
            writer.WriteLongValue("defaultTTLMs", DefaultTTLMs);
            writer.WriteBoolValue("enabled", Enabled);
            writer.WriteStringValue("message", Message);
            writer.WriteLongValue("ttlQueriesMs", TtlQueriesMs);
            writer.WriteLongValue("ttlResourcesMs", TtlResourcesMs);
            writer.WriteDateTimeOffsetValue("updated", Updated);
            writer.WriteBoolValue("useDefaultTTL", UseDefaultTTL);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
