// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Grafana.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum CreateSnapshotRequestDtoResourceTypesItem
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "DASHBOARD")]
        #pragma warning disable CS1591
        Dashboard,
        #pragma warning restore CS1591
        [EnumMember(Value = "DATASOURCE")]
        #pragma warning disable CS1591
        Datasource,
        #pragma warning restore CS1591
        [EnumMember(Value = "FOLDER")]
        #pragma warning disable CS1591
        Folder,
        #pragma warning restore CS1591
        [EnumMember(Value = "LIBRARY_ELEMENT")]
        #pragma warning disable CS1591
        LibraryElement,
        #pragma warning restore CS1591
        [EnumMember(Value = "ALERT_RULE")]
        #pragma warning disable CS1591
        AlertRule,
        #pragma warning restore CS1591
        [EnumMember(Value = "ALERT_RULE_GROUP")]
        #pragma warning disable CS1591
        AlertRuleGroup,
        #pragma warning restore CS1591
        [EnumMember(Value = "CONTACT_POINT")]
        #pragma warning disable CS1591
        ContactPoint,
        #pragma warning restore CS1591
        [EnumMember(Value = "NOTIFICATION_POLICY")]
        #pragma warning disable CS1591
        NotificationPolicy,
        #pragma warning restore CS1591
        [EnumMember(Value = "NOTIFICATION_TEMPLATE")]
        #pragma warning disable CS1591
        NotificationTemplate,
        #pragma warning restore CS1591
        [EnumMember(Value = "MUTE_TIMING")]
        #pragma warning disable CS1591
        MuteTiming,
        #pragma warning restore CS1591
        [EnumMember(Value = "PLUGIN")]
        #pragma warning disable CS1591
        Plugin,
        #pragma warning restore CS1591
    }
}
