// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Grafana.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CreateOrUpdateReport : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The dashboards property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Grafana.OpenApiClient.Models.ReportDashboard>? Dashboards { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Grafana.OpenApiClient.Models.ReportDashboard> Dashboards { get; set; }
#endif
        /// <summary>The enableCsv property</summary>
        public bool? EnableCsv { get; set; }
        /// <summary>The enableDashboardUrl property</summary>
        public bool? EnableDashboardUrl { get; set; }
        /// <summary>The formats property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Formats { get; set; }
#nullable restore
#else
        public List<string> Formats { get; set; }
#endif
        /// <summary>The message property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Message { get; set; }
#nullable restore
#else
        public string Message { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The options property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Grafana.OpenApiClient.Models.ReportOptions? Options { get; set; }
#nullable restore
#else
        public global::Soenneker.Grafana.OpenApiClient.Models.ReportOptions Options { get; set; }
#endif
        /// <summary>The recipients property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Recipients { get; set; }
#nullable restore
#else
        public string Recipients { get; set; }
#endif
        /// <summary>The replyTo property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ReplyTo { get; set; }
#nullable restore
#else
        public string ReplyTo { get; set; }
#endif
        /// <summary>The scaleFactor property</summary>
        public long? ScaleFactor { get; set; }
        /// <summary>The schedule property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Grafana.OpenApiClient.Models.ReportSchedule? Schedule { get; set; }
#nullable restore
#else
        public global::Soenneker.Grafana.OpenApiClient.Models.ReportSchedule Schedule { get; set; }
#endif
        /// <summary>+enum</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? State { get; set; }
#nullable restore
#else
        public string State { get; set; }
#endif
        /// <summary>The subject property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Subject { get; set; }
#nullable restore
#else
        public string Subject { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Grafana.OpenApiClient.Models.CreateOrUpdateReport"/> and sets the default values.
        /// </summary>
        public CreateOrUpdateReport()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Grafana.OpenApiClient.Models.CreateOrUpdateReport"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Grafana.OpenApiClient.Models.CreateOrUpdateReport CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Grafana.OpenApiClient.Models.CreateOrUpdateReport();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "dashboards", n => { Dashboards = n.GetCollectionOfObjectValues<global::Soenneker.Grafana.OpenApiClient.Models.ReportDashboard>(global::Soenneker.Grafana.OpenApiClient.Models.ReportDashboard.CreateFromDiscriminatorValue)?.AsList(); } },
                { "enableCsv", n => { EnableCsv = n.GetBoolValue(); } },
                { "enableDashboardUrl", n => { EnableDashboardUrl = n.GetBoolValue(); } },
                { "formats", n => { Formats = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "message", n => { Message = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "options", n => { Options = n.GetObjectValue<global::Soenneker.Grafana.OpenApiClient.Models.ReportOptions>(global::Soenneker.Grafana.OpenApiClient.Models.ReportOptions.CreateFromDiscriminatorValue); } },
                { "recipients", n => { Recipients = n.GetStringValue(); } },
                { "replyTo", n => { ReplyTo = n.GetStringValue(); } },
                { "scaleFactor", n => { ScaleFactor = n.GetLongValue(); } },
                { "schedule", n => { Schedule = n.GetObjectValue<global::Soenneker.Grafana.OpenApiClient.Models.ReportSchedule>(global::Soenneker.Grafana.OpenApiClient.Models.ReportSchedule.CreateFromDiscriminatorValue); } },
                { "state", n => { State = n.GetStringValue(); } },
                { "subject", n => { Subject = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Grafana.OpenApiClient.Models.ReportDashboard>("dashboards", Dashboards);
            writer.WriteBoolValue("enableCsv", EnableCsv);
            writer.WriteBoolValue("enableDashboardUrl", EnableDashboardUrl);
            writer.WriteCollectionOfPrimitiveValues<string>("formats", Formats);
            writer.WriteStringValue("message", Message);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Soenneker.Grafana.OpenApiClient.Models.ReportOptions>("options", Options);
            writer.WriteStringValue("recipients", Recipients);
            writer.WriteStringValue("replyTo", ReplyTo);
            writer.WriteLongValue("scaleFactor", ScaleFactor);
            writer.WriteObjectValue<global::Soenneker.Grafana.OpenApiClient.Models.ReportSchedule>("schedule", Schedule);
            writer.WriteStringValue("state", State);
            writer.WriteStringValue("subject", Subject);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
