// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Grafana.OpenApiClient.Models
{
    /// <summary>
    /// DashboardVersionMeta extends the DashboardVersionDTO with the namesassociated with the UserIds, overriding the field with the same name fromthe DashboardVersionDTO model.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DashboardVersionMeta : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The created property</summary>
        public DateTimeOffset? Created { get; set; }
        /// <summary>The createdBy property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedBy { get; set; }
#nullable restore
#else
        public string CreatedBy { get; set; }
#endif
        /// <summary>The dashboardId property</summary>
        public long? DashboardId { get; set; }
        /// <summary>The data property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Grafana.OpenApiClient.Models.Json? Data { get; set; }
#nullable restore
#else
        public global::Soenneker.Grafana.OpenApiClient.Models.Json Data { get; set; }
#endif
        /// <summary>The id property</summary>
        public long? Id { get; set; }
        /// <summary>The message property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Message { get; set; }
#nullable restore
#else
        public string Message { get; set; }
#endif
        /// <summary>The parentVersion property</summary>
        public long? ParentVersion { get; set; }
        /// <summary>The restoredFrom property</summary>
        public long? RestoredFrom { get; set; }
        /// <summary>The uid property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Uid { get; set; }
#nullable restore
#else
        public string Uid { get; set; }
#endif
        /// <summary>The version property</summary>
        public long? Version { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Grafana.OpenApiClient.Models.DashboardVersionMeta"/> and sets the default values.
        /// </summary>
        public DashboardVersionMeta()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Grafana.OpenApiClient.Models.DashboardVersionMeta"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Grafana.OpenApiClient.Models.DashboardVersionMeta CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Grafana.OpenApiClient.Models.DashboardVersionMeta();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "created", n => { Created = n.GetDateTimeOffsetValue(); } },
                { "createdBy", n => { CreatedBy = n.GetStringValue(); } },
                { "dashboardId", n => { DashboardId = n.GetLongValue(); } },
                { "data", n => { Data = n.GetObjectValue<global::Soenneker.Grafana.OpenApiClient.Models.Json>(global::Soenneker.Grafana.OpenApiClient.Models.Json.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetLongValue(); } },
                { "message", n => { Message = n.GetStringValue(); } },
                { "parentVersion", n => { ParentVersion = n.GetLongValue(); } },
                { "restoredFrom", n => { RestoredFrom = n.GetLongValue(); } },
                { "uid", n => { Uid = n.GetStringValue(); } },
                { "version", n => { Version = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("created", Created);
            writer.WriteStringValue("createdBy", CreatedBy);
            writer.WriteLongValue("dashboardId", DashboardId);
            writer.WriteObjectValue<global::Soenneker.Grafana.OpenApiClient.Models.Json>("data", Data);
            writer.WriteLongValue("id", Id);
            writer.WriteStringValue("message", Message);
            writer.WriteLongValue("parentVersion", ParentVersion);
            writer.WriteLongValue("restoredFrom", RestoredFrom);
            writer.WriteStringValue("uid", Uid);
            writer.WriteLongValue("version", Version);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
