// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Grafana.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum EmbeddedContactPoint_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "alertmanager")]
        #pragma warning disable CS1591
        Alertmanager,
        #pragma warning restore CS1591
        [EnumMember(Value = "dingding")]
        #pragma warning disable CS1591
        Dingding,
        #pragma warning restore CS1591
        [EnumMember(Value = "discord")]
        #pragma warning disable CS1591
        Discord,
        #pragma warning restore CS1591
        [EnumMember(Value = "email")]
        #pragma warning disable CS1591
        Email,
        #pragma warning restore CS1591
        [EnumMember(Value = "googlechat")]
        #pragma warning disable CS1591
        Googlechat,
        #pragma warning restore CS1591
        [EnumMember(Value = "kafka")]
        #pragma warning disable CS1591
        Kafka,
        #pragma warning restore CS1591
        [EnumMember(Value = "line")]
        #pragma warning disable CS1591
        Line,
        #pragma warning restore CS1591
        [EnumMember(Value = "opsgenie")]
        #pragma warning disable CS1591
        Opsgenie,
        #pragma warning restore CS1591
        [EnumMember(Value = "pagerduty")]
        #pragma warning disable CS1591
        Pagerduty,
        #pragma warning restore CS1591
        [EnumMember(Value = "pushover")]
        #pragma warning disable CS1591
        Pushover,
        #pragma warning restore CS1591
        [EnumMember(Value = "sensugo")]
        #pragma warning disable CS1591
        Sensugo,
        #pragma warning restore CS1591
        [EnumMember(Value = "slack")]
        #pragma warning disable CS1591
        Slack,
        #pragma warning restore CS1591
        [EnumMember(Value = "teams")]
        #pragma warning disable CS1591
        Teams,
        #pragma warning restore CS1591
        [EnumMember(Value = "telegram")]
        #pragma warning disable CS1591
        Telegram,
        #pragma warning restore CS1591
        [EnumMember(Value = "threema")]
        #pragma warning disable CS1591
        Threema,
        #pragma warning restore CS1591
        [EnumMember(Value = "victorops")]
        #pragma warning disable CS1591
        Victorops,
        #pragma warning restore CS1591
        [EnumMember(Value = "webhook")]
        #pragma warning disable CS1591
        Webhook,
        #pragma warning restore CS1591
        [EnumMember(Value = "wecom")]
        #pragma warning disable CS1591
        Wecom,
        #pragma warning restore CS1591
    }
}
