// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Grafana.OpenApiClient.Models
{
    /// <summary>
    /// EmbeddedContactPoint is the contact point type that is usedby grafanas embedded alertmanager implementation.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EmbeddedContactPoint : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The disableResolveMessage property</summary>
        public bool? DisableResolveMessage { get; set; }
        /// <summary>Name is used as grouping key in the UI. Contact points with thesame name will be grouped in the UI.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The provenance property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Provenance { get; private set; }
#nullable restore
#else
        public string Provenance { get; private set; }
#endif
        /// <summary>The settings property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Grafana.OpenApiClient.Models.Json? Settings { get; set; }
#nullable restore
#else
        public global::Soenneker.Grafana.OpenApiClient.Models.Json Settings { get; set; }
#endif
        /// <summary>The type property</summary>
        public global::Soenneker.Grafana.OpenApiClient.Models.EmbeddedContactPoint_type? Type { get; set; }
        /// <summary>UID is the unique identifier of the contact point. The UID can beset by the user.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Uid { get; set; }
#nullable restore
#else
        public string Uid { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Grafana.OpenApiClient.Models.EmbeddedContactPoint"/> and sets the default values.
        /// </summary>
        public EmbeddedContactPoint()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Grafana.OpenApiClient.Models.EmbeddedContactPoint"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Grafana.OpenApiClient.Models.EmbeddedContactPoint CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Grafana.OpenApiClient.Models.EmbeddedContactPoint();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "disableResolveMessage", n => { DisableResolveMessage = n.GetBoolValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "provenance", n => { Provenance = n.GetStringValue(); } },
                { "settings", n => { Settings = n.GetObjectValue<global::Soenneker.Grafana.OpenApiClient.Models.Json>(global::Soenneker.Grafana.OpenApiClient.Models.Json.CreateFromDiscriminatorValue); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Grafana.OpenApiClient.Models.EmbeddedContactPoint_type>(); } },
                { "uid", n => { Uid = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("disableResolveMessage", DisableResolveMessage);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Soenneker.Grafana.OpenApiClient.Models.Json>("settings", Settings);
            writer.WriteEnumValue<global::Soenneker.Grafana.OpenApiClient.Models.EmbeddedContactPoint_type>("type", Type);
            writer.WriteStringValue("uid", Uid);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
