// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Grafana.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetSnapshotResponseDtoStatus
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "INITIALIZING")]
        #pragma warning disable CS1591
        Initializing,
        #pragma warning restore CS1591
        [EnumMember(Value = "CREATING")]
        #pragma warning disable CS1591
        Creating,
        #pragma warning restore CS1591
        [EnumMember(Value = "PENDING_UPLOAD")]
        #pragma warning disable CS1591
        PendingUpload,
        #pragma warning restore CS1591
        [EnumMember(Value = "UPLOADING")]
        #pragma warning disable CS1591
        Uploading,
        #pragma warning restore CS1591
        [EnumMember(Value = "PENDING_PROCESSING")]
        #pragma warning disable CS1591
        PendingProcessing,
        #pragma warning restore CS1591
        [EnumMember(Value = "PROCESSING")]
        #pragma warning disable CS1591
        Processing,
        #pragma warning restore CS1591
        [EnumMember(Value = "FINISHED")]
        #pragma warning disable CS1591
        Finished,
        #pragma warning restore CS1591
        [EnumMember(Value = "CANCELED")]
        #pragma warning disable CS1591
        Canceled,
        #pragma warning restore CS1591
        [EnumMember(Value = "ERROR")]
        #pragma warning disable CS1591
        Error,
        #pragma warning restore CS1591
        [EnumMember(Value = "UNKNOWN")]
        #pragma warning disable CS1591
        Unknown,
        #pragma warning restore CS1591
    }
}
