// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Grafana.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ImportDashboardRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The dashboard property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Grafana.OpenApiClient.Models.Json? Dashboard { get; set; }
#nullable restore
#else
        public global::Soenneker.Grafana.OpenApiClient.Models.Json Dashboard { get; set; }
#endif
        /// <summary>Deprecated: use FolderUID instead</summary>
        public long? FolderId { get; set; }
        /// <summary>The folderUid property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FolderUid { get; set; }
#nullable restore
#else
        public string FolderUid { get; set; }
#endif
        /// <summary>The inputs property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Grafana.OpenApiClient.Models.ImportDashboardInput>? Inputs { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Grafana.OpenApiClient.Models.ImportDashboardInput> Inputs { get; set; }
#endif
        /// <summary>The overwrite property</summary>
        public bool? Overwrite { get; set; }
        /// <summary>The path property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Path { get; set; }
#nullable restore
#else
        public string Path { get; set; }
#endif
        /// <summary>The pluginId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PluginId { get; set; }
#nullable restore
#else
        public string PluginId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Grafana.OpenApiClient.Models.ImportDashboardRequest"/> and sets the default values.
        /// </summary>
        public ImportDashboardRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Grafana.OpenApiClient.Models.ImportDashboardRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Grafana.OpenApiClient.Models.ImportDashboardRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Grafana.OpenApiClient.Models.ImportDashboardRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "dashboard", n => { Dashboard = n.GetObjectValue<global::Soenneker.Grafana.OpenApiClient.Models.Json>(global::Soenneker.Grafana.OpenApiClient.Models.Json.CreateFromDiscriminatorValue); } },
                { "folderId", n => { FolderId = n.GetLongValue(); } },
                { "folderUid", n => { FolderUid = n.GetStringValue(); } },
                { "inputs", n => { Inputs = n.GetCollectionOfObjectValues<global::Soenneker.Grafana.OpenApiClient.Models.ImportDashboardInput>(global::Soenneker.Grafana.OpenApiClient.Models.ImportDashboardInput.CreateFromDiscriminatorValue)?.AsList(); } },
                { "overwrite", n => { Overwrite = n.GetBoolValue(); } },
                { "path", n => { Path = n.GetStringValue(); } },
                { "pluginId", n => { PluginId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Grafana.OpenApiClient.Models.Json>("dashboard", Dashboard);
            writer.WriteLongValue("folderId", FolderId);
            writer.WriteStringValue("folderUid", FolderUid);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Grafana.OpenApiClient.Models.ImportDashboardInput>("inputs", Inputs);
            writer.WriteBoolValue("overwrite", Overwrite);
            writer.WriteStringValue("path", Path);
            writer.WriteStringValue("pluginId", PluginId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
