// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Grafana.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum MigrateDataResponseItemDTO_errorCode
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "ALERT_RULES_QUOTA_REACHED")]
        #pragma warning disable CS1591
        ALERT_RULES_QUOTA_REACHED,
        #pragma warning restore CS1591
        [EnumMember(Value = "ALERT_RULES_GROUP_QUOTA_REACHED")]
        #pragma warning disable CS1591
        ALERT_RULES_GROUP_QUOTA_REACHED,
        #pragma warning restore CS1591
        [EnumMember(Value = "DATASOURCE_NAME_CONFLICT")]
        #pragma warning disable CS1591
        DATASOURCE_NAME_CONFLICT,
        #pragma warning restore CS1591
        [EnumMember(Value = "DATASOURCE_INVALID_URL")]
        #pragma warning disable CS1591
        DATASOURCE_INVALID_URL,
        #pragma warning restore CS1591
        [EnumMember(Value = "DATASOURCE_ALREADY_MANAGED")]
        #pragma warning disable CS1591
        DATASOURCE_ALREADY_MANAGED,
        #pragma warning restore CS1591
        [EnumMember(Value = "FOLDER_NAME_CONFLICT")]
        #pragma warning disable CS1591
        FOLDER_NAME_CONFLICT,
        #pragma warning restore CS1591
        [EnumMember(Value = "DASHBOARD_ALREADY_MANAGED")]
        #pragma warning disable CS1591
        DASHBOARD_ALREADY_MANAGED,
        #pragma warning restore CS1591
        [EnumMember(Value = "LIBRARY_ELEMENT_NAME_CONFLICT")]
        #pragma warning disable CS1591
        LIBRARY_ELEMENT_NAME_CONFLICT,
        #pragma warning restore CS1591
        [EnumMember(Value = "UNSUPPORTED_DATA_TYPE")]
        #pragma warning disable CS1591
        UNSUPPORTED_DATA_TYPE,
        #pragma warning restore CS1591
        [EnumMember(Value = "RESOURCE_CONFLICT")]
        #pragma warning disable CS1591
        RESOURCE_CONFLICT,
        #pragma warning restore CS1591
        [EnumMember(Value = "UNEXPECTED_STATUS_CODE")]
        #pragma warning disable CS1591
        UNEXPECTED_STATUS_CODE,
        #pragma warning restore CS1591
        [EnumMember(Value = "INTERNAL_SERVICE_ERROR")]
        #pragma warning disable CS1591
        INTERNAL_SERVICE_ERROR,
        #pragma warning restore CS1591
        [EnumMember(Value = "GENERIC_ERROR")]
        #pragma warning disable CS1591
        GENERIC_ERROR,
        #pragma warning restore CS1591
    }
}
