// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Grafana.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ProvisionedAlertRule : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The annotations property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Grafana.OpenApiClient.Models.ProvisionedAlertRule_annotations? Annotations { get; set; }
#nullable restore
#else
        public global::Soenneker.Grafana.OpenApiClient.Models.ProvisionedAlertRule_annotations Annotations { get; set; }
#endif
        /// <summary>The condition property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Condition { get; set; }
#nullable restore
#else
        public string Condition { get; set; }
#endif
        /// <summary>The data property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Grafana.OpenApiClient.Models.AlertQuery>? Data { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Grafana.OpenApiClient.Models.AlertQuery> Data { get; set; }
#endif
        /// <summary>The execErrState property</summary>
        public global::Soenneker.Grafana.OpenApiClient.Models.ProvisionedAlertRule_execErrState? ExecErrState { get; set; }
        /// <summary>The folderUID property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FolderUID { get; set; }
#nullable restore
#else
        public string FolderUID { get; set; }
#endif
        /// <summary>The for property</summary>
        public TimeSpan? For { get; set; }
        /// <summary>The id property</summary>
        public long? Id { get; set; }
        /// <summary>The isPaused property</summary>
        public bool? IsPaused { get; set; }
        /// <summary>The keep_firing_for property</summary>
        public TimeSpan? KeepFiringFor { get; set; }
        /// <summary>The labels property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Grafana.OpenApiClient.Models.ProvisionedAlertRule_labels? Labels { get; set; }
#nullable restore
#else
        public global::Soenneker.Grafana.OpenApiClient.Models.ProvisionedAlertRule_labels Labels { get; set; }
#endif
        /// <summary>The missingSeriesEvalsToResolve property</summary>
        public long? MissingSeriesEvalsToResolve { get; set; }
        /// <summary>The noDataState property</summary>
        public global::Soenneker.Grafana.OpenApiClient.Models.ProvisionedAlertRule_noDataState? NoDataState { get; set; }
        /// <summary>The notification_settings property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Grafana.OpenApiClient.Models.AlertRuleNotificationSettings? NotificationSettings { get; set; }
#nullable restore
#else
        public global::Soenneker.Grafana.OpenApiClient.Models.AlertRuleNotificationSettings NotificationSettings { get; set; }
#endif
        /// <summary>The orgID property</summary>
        public long? OrgID { get; set; }
        /// <summary>The provenance property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Provenance { get; set; }
#nullable restore
#else
        public string Provenance { get; set; }
#endif
        /// <summary>The record property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Grafana.OpenApiClient.Models.Record? Record { get; set; }
#nullable restore
#else
        public global::Soenneker.Grafana.OpenApiClient.Models.Record Record { get; set; }
#endif
        /// <summary>The ruleGroup property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RuleGroup { get; set; }
#nullable restore
#else
        public string RuleGroup { get; set; }
#endif
        /// <summary>The title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>The uid property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Uid { get; set; }
#nullable restore
#else
        public string Uid { get; set; }
#endif
        /// <summary>The updated property</summary>
        public DateTimeOffset? Updated { get; private set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Grafana.OpenApiClient.Models.ProvisionedAlertRule"/> and sets the default values.
        /// </summary>
        public ProvisionedAlertRule()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Grafana.OpenApiClient.Models.ProvisionedAlertRule"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Grafana.OpenApiClient.Models.ProvisionedAlertRule CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Grafana.OpenApiClient.Models.ProvisionedAlertRule();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "annotations", n => { Annotations = n.GetObjectValue<global::Soenneker.Grafana.OpenApiClient.Models.ProvisionedAlertRule_annotations>(global::Soenneker.Grafana.OpenApiClient.Models.ProvisionedAlertRule_annotations.CreateFromDiscriminatorValue); } },
                { "condition", n => { Condition = n.GetStringValue(); } },
                { "data", n => { Data = n.GetCollectionOfObjectValues<global::Soenneker.Grafana.OpenApiClient.Models.AlertQuery>(global::Soenneker.Grafana.OpenApiClient.Models.AlertQuery.CreateFromDiscriminatorValue)?.AsList(); } },
                { "execErrState", n => { ExecErrState = n.GetEnumValue<global::Soenneker.Grafana.OpenApiClient.Models.ProvisionedAlertRule_execErrState>(); } },
                { "folderUID", n => { FolderUID = n.GetStringValue(); } },
                { "for", n => { For = n.GetTimeSpanValue(); } },
                { "id", n => { Id = n.GetLongValue(); } },
                { "isPaused", n => { IsPaused = n.GetBoolValue(); } },
                { "keep_firing_for", n => { KeepFiringFor = n.GetTimeSpanValue(); } },
                { "labels", n => { Labels = n.GetObjectValue<global::Soenneker.Grafana.OpenApiClient.Models.ProvisionedAlertRule_labels>(global::Soenneker.Grafana.OpenApiClient.Models.ProvisionedAlertRule_labels.CreateFromDiscriminatorValue); } },
                { "missingSeriesEvalsToResolve", n => { MissingSeriesEvalsToResolve = n.GetLongValue(); } },
                { "noDataState", n => { NoDataState = n.GetEnumValue<global::Soenneker.Grafana.OpenApiClient.Models.ProvisionedAlertRule_noDataState>(); } },
                { "notification_settings", n => { NotificationSettings = n.GetObjectValue<global::Soenneker.Grafana.OpenApiClient.Models.AlertRuleNotificationSettings>(global::Soenneker.Grafana.OpenApiClient.Models.AlertRuleNotificationSettings.CreateFromDiscriminatorValue); } },
                { "orgID", n => { OrgID = n.GetLongValue(); } },
                { "provenance", n => { Provenance = n.GetStringValue(); } },
                { "record", n => { Record = n.GetObjectValue<global::Soenneker.Grafana.OpenApiClient.Models.Record>(global::Soenneker.Grafana.OpenApiClient.Models.Record.CreateFromDiscriminatorValue); } },
                { "ruleGroup", n => { RuleGroup = n.GetStringValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "uid", n => { Uid = n.GetStringValue(); } },
                { "updated", n => { Updated = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Grafana.OpenApiClient.Models.ProvisionedAlertRule_annotations>("annotations", Annotations);
            writer.WriteStringValue("condition", Condition);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Grafana.OpenApiClient.Models.AlertQuery>("data", Data);
            writer.WriteEnumValue<global::Soenneker.Grafana.OpenApiClient.Models.ProvisionedAlertRule_execErrState>("execErrState", ExecErrState);
            writer.WriteStringValue("folderUID", FolderUID);
            writer.WriteTimeSpanValue("for", For);
            writer.WriteLongValue("id", Id);
            writer.WriteBoolValue("isPaused", IsPaused);
            writer.WriteTimeSpanValue("keep_firing_for", KeepFiringFor);
            writer.WriteObjectValue<global::Soenneker.Grafana.OpenApiClient.Models.ProvisionedAlertRule_labels>("labels", Labels);
            writer.WriteLongValue("missingSeriesEvalsToResolve", MissingSeriesEvalsToResolve);
            writer.WriteEnumValue<global::Soenneker.Grafana.OpenApiClient.Models.ProvisionedAlertRule_noDataState>("noDataState", NoDataState);
            writer.WriteObjectValue<global::Soenneker.Grafana.OpenApiClient.Models.AlertRuleNotificationSettings>("notification_settings", NotificationSettings);
            writer.WriteLongValue("orgID", OrgID);
            writer.WriteStringValue("provenance", Provenance);
            writer.WriteObjectValue<global::Soenneker.Grafana.OpenApiClient.Models.Record>("record", Record);
            writer.WriteStringValue("ruleGroup", RuleGroup);
            writer.WriteStringValue("title", Title);
            writer.WriteStringValue("uid", Uid);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
