// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Grafana.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PublicDashboard : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The accessToken property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccessToken { get; set; }
#nullable restore
#else
        public string AccessToken { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The annotationsEnabled property</summary>
        public bool? AnnotationsEnabled { get; set; }
        /// <summary>The createdAt property</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The createdBy property</summary>
        public long? CreatedBy { get; set; }
        /// <summary>The dashboardUid property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DashboardUid { get; set; }
#nullable restore
#else
        public string DashboardUid { get; set; }
#endif
        /// <summary>The isEnabled property</summary>
        public bool? IsEnabled { get; set; }
        /// <summary>The recipients property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Grafana.OpenApiClient.Models.EmailDTO>? Recipients { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Grafana.OpenApiClient.Models.EmailDTO> Recipients { get; set; }
#endif
        /// <summary>The share property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Share { get; set; }
#nullable restore
#else
        public string Share { get; set; }
#endif
        /// <summary>The timeSelectionEnabled property</summary>
        public bool? TimeSelectionEnabled { get; set; }
        /// <summary>The uid property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Uid { get; set; }
#nullable restore
#else
        public string Uid { get; set; }
#endif
        /// <summary>The updatedAt property</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>The updatedBy property</summary>
        public long? UpdatedBy { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Grafana.OpenApiClient.Models.PublicDashboard"/> and sets the default values.
        /// </summary>
        public PublicDashboard()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Grafana.OpenApiClient.Models.PublicDashboard"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Grafana.OpenApiClient.Models.PublicDashboard CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Grafana.OpenApiClient.Models.PublicDashboard();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "accessToken", n => { AccessToken = n.GetStringValue(); } },
                { "annotationsEnabled", n => { AnnotationsEnabled = n.GetBoolValue(); } },
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "createdBy", n => { CreatedBy = n.GetLongValue(); } },
                { "dashboardUid", n => { DashboardUid = n.GetStringValue(); } },
                { "isEnabled", n => { IsEnabled = n.GetBoolValue(); } },
                { "recipients", n => { Recipients = n.GetCollectionOfObjectValues<global::Soenneker.Grafana.OpenApiClient.Models.EmailDTO>(global::Soenneker.Grafana.OpenApiClient.Models.EmailDTO.CreateFromDiscriminatorValue)?.AsList(); } },
                { "share", n => { Share = n.GetStringValue(); } },
                { "timeSelectionEnabled", n => { TimeSelectionEnabled = n.GetBoolValue(); } },
                { "uid", n => { Uid = n.GetStringValue(); } },
                { "updatedAt", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
                { "updatedBy", n => { UpdatedBy = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("accessToken", AccessToken);
            writer.WriteBoolValue("annotationsEnabled", AnnotationsEnabled);
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteLongValue("createdBy", CreatedBy);
            writer.WriteStringValue("dashboardUid", DashboardUid);
            writer.WriteBoolValue("isEnabled", IsEnabled);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Grafana.OpenApiClient.Models.EmailDTO>("recipients", Recipients);
            writer.WriteStringValue("share", Share);
            writer.WriteBoolValue("timeSelectionEnabled", TimeSelectionEnabled);
            writer.WriteStringValue("uid", Uid);
            writer.WriteDateTimeOffsetValue("updatedAt", UpdatedAt);
            writer.WriteLongValue("updatedBy", UpdatedBy);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
