// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Grafana.OpenApiClient.Models
{
    /// <summary>
    /// RecordingRuleJSON is the external representation of a recording rule
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RecordingRuleJSON : IAdditionalDataHolder, IParsable
    {
        /// <summary>The active property</summary>
        public bool? Active { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The count property</summary>
        public bool? Count { get; set; }
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The dest_data_source_uid property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DestDataSourceUid { get; set; }
#nullable restore
#else
        public string DestDataSourceUid { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The interval property</summary>
        public long? Interval { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The prom_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PromName { get; set; }
#nullable restore
#else
        public string PromName { get; set; }
#endif
        /// <summary>The queries property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Grafana.OpenApiClient.Models.RecordingRuleJSON_queries>? Queries { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Grafana.OpenApiClient.Models.RecordingRuleJSON_queries> Queries { get; set; }
#endif
        /// <summary>The range property</summary>
        public long? Range { get; set; }
        /// <summary>The target_ref_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TargetRefId { get; set; }
#nullable restore
#else
        public string TargetRefId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Grafana.OpenApiClient.Models.RecordingRuleJSON"/> and sets the default values.
        /// </summary>
        public RecordingRuleJSON()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Grafana.OpenApiClient.Models.RecordingRuleJSON"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Grafana.OpenApiClient.Models.RecordingRuleJSON CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Grafana.OpenApiClient.Models.RecordingRuleJSON();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "active", n => { Active = n.GetBoolValue(); } },
                { "count", n => { Count = n.GetBoolValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "dest_data_source_uid", n => { DestDataSourceUid = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "interval", n => { Interval = n.GetLongValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "prom_name", n => { PromName = n.GetStringValue(); } },
                { "queries", n => { Queries = n.GetCollectionOfObjectValues<global::Soenneker.Grafana.OpenApiClient.Models.RecordingRuleJSON_queries>(global::Soenneker.Grafana.OpenApiClient.Models.RecordingRuleJSON_queries.CreateFromDiscriminatorValue)?.AsList(); } },
                { "range", n => { Range = n.GetLongValue(); } },
                { "target_ref_id", n => { TargetRefId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("active", Active);
            writer.WriteBoolValue("count", Count);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("dest_data_source_uid", DestDataSourceUid);
            writer.WriteStringValue("id", Id);
            writer.WriteLongValue("interval", Interval);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("prom_name", PromName);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Grafana.OpenApiClient.Models.RecordingRuleJSON_queries>("queries", Queries);
            writer.WriteLongValue("range", Range);
            writer.WriteStringValue("target_ref_id", TargetRefId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
