// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Grafana.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ReportSettings : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The branding property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Grafana.OpenApiClient.Models.ReportBrandingOptions? Branding { get; set; }
#nullable restore
#else
        public global::Soenneker.Grafana.OpenApiClient.Models.ReportBrandingOptions Branding { get; set; }
#endif
        /// <summary>The embeddedImageTheme property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EmbeddedImageTheme { get; set; }
#nullable restore
#else
        public string EmbeddedImageTheme { get; set; }
#endif
        /// <summary>The footerFontFamily property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FooterFontFamily { get; set; }
#nullable restore
#else
        public string FooterFontFamily { get; set; }
#endif
        /// <summary>The footerItems property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Grafana.OpenApiClient.Models.FooterItem>? FooterItems { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Grafana.OpenApiClient.Models.FooterItem> FooterItems { get; set; }
#endif
        /// <summary>The id property</summary>
        public long? Id { get; set; }
        /// <summary>The orgId property</summary>
        public long? OrgId { get; set; }
        /// <summary>The pdfDashboardTitleEnabled property</summary>
        public bool? PdfDashboardTitleEnabled { get; set; }
        /// <summary>The pdfHeaderEnabled property</summary>
        public bool? PdfHeaderEnabled { get; set; }
        /// <summary>The pdfTheme property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PdfTheme { get; set; }
#nullable restore
#else
        public string PdfTheme { get; set; }
#endif
        /// <summary>The pdfTimeRangeEnabled property</summary>
        public bool? PdfTimeRangeEnabled { get; set; }
        /// <summary>The userId property</summary>
        public long? UserId { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Grafana.OpenApiClient.Models.ReportSettings"/> and sets the default values.
        /// </summary>
        public ReportSettings()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Grafana.OpenApiClient.Models.ReportSettings"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Grafana.OpenApiClient.Models.ReportSettings CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Grafana.OpenApiClient.Models.ReportSettings();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "branding", n => { Branding = n.GetObjectValue<global::Soenneker.Grafana.OpenApiClient.Models.ReportBrandingOptions>(global::Soenneker.Grafana.OpenApiClient.Models.ReportBrandingOptions.CreateFromDiscriminatorValue); } },
                { "embeddedImageTheme", n => { EmbeddedImageTheme = n.GetStringValue(); } },
                { "footerFontFamily", n => { FooterFontFamily = n.GetStringValue(); } },
                { "footerItems", n => { FooterItems = n.GetCollectionOfObjectValues<global::Soenneker.Grafana.OpenApiClient.Models.FooterItem>(global::Soenneker.Grafana.OpenApiClient.Models.FooterItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "id", n => { Id = n.GetLongValue(); } },
                { "orgId", n => { OrgId = n.GetLongValue(); } },
                { "pdfDashboardTitleEnabled", n => { PdfDashboardTitleEnabled = n.GetBoolValue(); } },
                { "pdfHeaderEnabled", n => { PdfHeaderEnabled = n.GetBoolValue(); } },
                { "pdfTheme", n => { PdfTheme = n.GetStringValue(); } },
                { "pdfTimeRangeEnabled", n => { PdfTimeRangeEnabled = n.GetBoolValue(); } },
                { "userId", n => { UserId = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Grafana.OpenApiClient.Models.ReportBrandingOptions>("branding", Branding);
            writer.WriteStringValue("embeddedImageTheme", EmbeddedImageTheme);
            writer.WriteStringValue("footerFontFamily", FooterFontFamily);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Grafana.OpenApiClient.Models.FooterItem>("footerItems", FooterItems);
            writer.WriteLongValue("id", Id);
            writer.WriteLongValue("orgId", OrgId);
            writer.WriteBoolValue("pdfDashboardTitleEnabled", PdfDashboardTitleEnabled);
            writer.WriteBoolValue("pdfHeaderEnabled", PdfHeaderEnabled);
            writer.WriteStringValue("pdfTheme", PdfTheme);
            writer.WriteBoolValue("pdfTimeRangeEnabled", PdfTimeRangeEnabled);
            writer.WriteLongValue("userId", UserId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
