// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Grafana.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum SearchQueriesSortParameter
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "time-desc")]
        #pragma warning disable CS1591
        TimeDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "time-asc")]
        #pragma warning disable CS1591
        TimeAsc,
        #pragma warning restore CS1591
    }
}
