// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Grafana.OpenApiClient.Models
{
    /// <summary>
    /// swagger: model
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ServiceAccountDTO : IAdditionalDataHolder, IParsable
    {
        /// <summary>The accessControl property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Grafana.OpenApiClient.Models.ServiceAccountDTO_accessControl? AccessControl { get; set; }
#nullable restore
#else
        public global::Soenneker.Grafana.OpenApiClient.Models.ServiceAccountDTO_accessControl AccessControl { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The avatarUrl property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AvatarUrl { get; set; }
#nullable restore
#else
        public string AvatarUrl { get; set; }
#endif
        /// <summary>The id property</summary>
        public long? Id { get; set; }
        /// <summary>The isDisabled property</summary>
        public bool? IsDisabled { get; set; }
        /// <summary>The isExternal property</summary>
        public bool? IsExternal { get; set; }
        /// <summary>The login property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Login { get; set; }
#nullable restore
#else
        public string Login { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The orgId property</summary>
        public long? OrgId { get; set; }
        /// <summary>The role property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Role { get; set; }
#nullable restore
#else
        public string Role { get; set; }
#endif
        /// <summary>The tokens property</summary>
        public long? Tokens { get; set; }
        /// <summary>The uid property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Uid { get; set; }
#nullable restore
#else
        public string Uid { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Grafana.OpenApiClient.Models.ServiceAccountDTO"/> and sets the default values.
        /// </summary>
        public ServiceAccountDTO()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Grafana.OpenApiClient.Models.ServiceAccountDTO"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Grafana.OpenApiClient.Models.ServiceAccountDTO CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Grafana.OpenApiClient.Models.ServiceAccountDTO();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "accessControl", n => { AccessControl = n.GetObjectValue<global::Soenneker.Grafana.OpenApiClient.Models.ServiceAccountDTO_accessControl>(global::Soenneker.Grafana.OpenApiClient.Models.ServiceAccountDTO_accessControl.CreateFromDiscriminatorValue); } },
                { "avatarUrl", n => { AvatarUrl = n.GetStringValue(); } },
                { "id", n => { Id = n.GetLongValue(); } },
                { "isDisabled", n => { IsDisabled = n.GetBoolValue(); } },
                { "isExternal", n => { IsExternal = n.GetBoolValue(); } },
                { "login", n => { Login = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "orgId", n => { OrgId = n.GetLongValue(); } },
                { "role", n => { Role = n.GetStringValue(); } },
                { "tokens", n => { Tokens = n.GetLongValue(); } },
                { "uid", n => { Uid = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Grafana.OpenApiClient.Models.ServiceAccountDTO_accessControl>("accessControl", AccessControl);
            writer.WriteStringValue("avatarUrl", AvatarUrl);
            writer.WriteLongValue("id", Id);
            writer.WriteBoolValue("isDisabled", IsDisabled);
            writer.WriteBoolValue("isExternal", IsExternal);
            writer.WriteStringValue("login", Login);
            writer.WriteStringValue("name", Name);
            writer.WriteLongValue("orgId", OrgId);
            writer.WriteStringValue("role", Role);
            writer.WriteLongValue("tokens", Tokens);
            writer.WriteStringValue("uid", Uid);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
