// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Grafana.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TokenDTO : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The created property</summary>
        public DateTimeOffset? Created { get; set; }
        /// <summary>The expiration property</summary>
        public DateTimeOffset? Expiration { get; set; }
        /// <summary>The hasExpired property</summary>
        public bool? HasExpired { get; set; }
        /// <summary>The id property</summary>
        public long? Id { get; set; }
        /// <summary>The isRevoked property</summary>
        public bool? IsRevoked { get; set; }
        /// <summary>The lastUsedAt property</summary>
        public DateTimeOffset? LastUsedAt { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The secondsUntilExpiration property</summary>
        public double? SecondsUntilExpiration { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Grafana.OpenApiClient.Models.TokenDTO"/> and sets the default values.
        /// </summary>
        public TokenDTO()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Grafana.OpenApiClient.Models.TokenDTO"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Grafana.OpenApiClient.Models.TokenDTO CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Grafana.OpenApiClient.Models.TokenDTO();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "created", n => { Created = n.GetDateTimeOffsetValue(); } },
                { "expiration", n => { Expiration = n.GetDateTimeOffsetValue(); } },
                { "hasExpired", n => { HasExpired = n.GetBoolValue(); } },
                { "id", n => { Id = n.GetLongValue(); } },
                { "isRevoked", n => { IsRevoked = n.GetBoolValue(); } },
                { "lastUsedAt", n => { LastUsedAt = n.GetDateTimeOffsetValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "secondsUntilExpiration", n => { SecondsUntilExpiration = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("created", Created);
            writer.WriteDateTimeOffsetValue("expiration", Expiration);
            writer.WriteBoolValue("hasExpired", HasExpired);
            writer.WriteLongValue("id", Id);
            writer.WriteBoolValue("isRevoked", IsRevoked);
            writer.WriteDateTimeOffsetValue("lastUsedAt", LastUsedAt);
            writer.WriteStringValue("name", Name);
            writer.WriteDoubleValue("secondsUntilExpiration", SecondsUntilExpiration);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
