// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Grafana.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UpdatePrefsCmd : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The numerical :id of a favorited dashboard</summary>
        public long? HomeDashboardId { get; set; }
        /// <summary>The homeDashboardUID property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HomeDashboardUID { get; set; }
#nullable restore
#else
        public string HomeDashboardUID { get; set; }
#endif
        /// <summary>The language property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Language { get; set; }
#nullable restore
#else
        public string Language { get; set; }
#endif
        /// <summary>The navbar property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Grafana.OpenApiClient.Models.NavbarPreference? Navbar { get; set; }
#nullable restore
#else
        public global::Soenneker.Grafana.OpenApiClient.Models.NavbarPreference Navbar { get; set; }
#endif
        /// <summary>The queryHistory property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Grafana.OpenApiClient.Models.QueryHistoryPreference? QueryHistory { get; set; }
#nullable restore
#else
        public global::Soenneker.Grafana.OpenApiClient.Models.QueryHistoryPreference QueryHistory { get; set; }
#endif
        /// <summary>The regionalFormat property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RegionalFormat { get; set; }
#nullable restore
#else
        public string RegionalFormat { get; set; }
#endif
        /// <summary>The theme property</summary>
        public global::Soenneker.Grafana.OpenApiClient.Models.UpdatePrefsCmd_theme? Theme { get; set; }
        /// <summary>Any IANA timezone string (e.g. America/New_York), &apos;utc&apos;, &apos;browser&apos;, or empty string</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Timezone { get; set; }
#nullable restore
#else
        public string Timezone { get; set; }
#endif
        /// <summary>The weekStart property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WeekStart { get; set; }
#nullable restore
#else
        public string WeekStart { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Grafana.OpenApiClient.Models.UpdatePrefsCmd"/> and sets the default values.
        /// </summary>
        public UpdatePrefsCmd()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Grafana.OpenApiClient.Models.UpdatePrefsCmd"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Grafana.OpenApiClient.Models.UpdatePrefsCmd CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Grafana.OpenApiClient.Models.UpdatePrefsCmd();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "homeDashboardId", n => { HomeDashboardId = n.GetLongValue(); } },
                { "homeDashboardUID", n => { HomeDashboardUID = n.GetStringValue(); } },
                { "language", n => { Language = n.GetStringValue(); } },
                { "navbar", n => { Navbar = n.GetObjectValue<global::Soenneker.Grafana.OpenApiClient.Models.NavbarPreference>(global::Soenneker.Grafana.OpenApiClient.Models.NavbarPreference.CreateFromDiscriminatorValue); } },
                { "queryHistory", n => { QueryHistory = n.GetObjectValue<global::Soenneker.Grafana.OpenApiClient.Models.QueryHistoryPreference>(global::Soenneker.Grafana.OpenApiClient.Models.QueryHistoryPreference.CreateFromDiscriminatorValue); } },
                { "regionalFormat", n => { RegionalFormat = n.GetStringValue(); } },
                { "theme", n => { Theme = n.GetEnumValue<global::Soenneker.Grafana.OpenApiClient.Models.UpdatePrefsCmd_theme>(); } },
                { "timezone", n => { Timezone = n.GetStringValue(); } },
                { "weekStart", n => { WeekStart = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteLongValue("homeDashboardId", HomeDashboardId);
            writer.WriteStringValue("homeDashboardUID", HomeDashboardUID);
            writer.WriteStringValue("language", Language);
            writer.WriteObjectValue<global::Soenneker.Grafana.OpenApiClient.Models.NavbarPreference>("navbar", Navbar);
            writer.WriteObjectValue<global::Soenneker.Grafana.OpenApiClient.Models.QueryHistoryPreference>("queryHistory", QueryHistory);
            writer.WriteStringValue("regionalFormat", RegionalFormat);
            writer.WriteEnumValue<global::Soenneker.Grafana.OpenApiClient.Models.UpdatePrefsCmd_theme>("theme", Theme);
            writer.WriteStringValue("timezone", Timezone);
            writer.WriteStringValue("weekStart", WeekStart);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
