// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Grafana.OpenApiClient.Saml.Acs;
using Soenneker.Grafana.OpenApiClient.Saml.Metadata;
using Soenneker.Grafana.OpenApiClient.Saml.Slo;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Grafana.OpenApiClient.Saml
{
    /// <summary>
    /// Builds and executes requests for operations under \saml
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SamlRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The acs property</summary>
        public global::Soenneker.Grafana.OpenApiClient.Saml.Acs.AcsRequestBuilder Acs
        {
            get => new global::Soenneker.Grafana.OpenApiClient.Saml.Acs.AcsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The metadata property</summary>
        public global::Soenneker.Grafana.OpenApiClient.Saml.Metadata.MetadataRequestBuilder Metadata
        {
            get => new global::Soenneker.Grafana.OpenApiClient.Saml.Metadata.MetadataRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The slo property</summary>
        public global::Soenneker.Grafana.OpenApiClient.Saml.Slo.SloRequestBuilder Slo
        {
            get => new global::Soenneker.Grafana.OpenApiClient.Saml.Slo.SloRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Grafana.OpenApiClient.Saml.SamlRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SamlRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/saml", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Grafana.OpenApiClient.Saml.SamlRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SamlRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/saml", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
