// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Grafana.OpenApiClient.Datasources.Item.Cache;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Grafana.OpenApiClient.Datasources.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \datasources\{dataSourceUID}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithDataSourceUItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The cache property</summary>
        public global::Soenneker.Grafana.OpenApiClient.Datasources.Item.Cache.CacheRequestBuilder Cache
        {
            get => new global::Soenneker.Grafana.OpenApiClient.Datasources.Item.Cache.CacheRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Grafana.OpenApiClient.Datasources.Item.WithDataSourceUItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithDataSourceUItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/datasources/{dataSourceUID}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Grafana.OpenApiClient.Datasources.Item.WithDataSourceUItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithDataSourceUItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/datasources/{dataSourceUID}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
