// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Grafana.OpenApiClient.ConvertNamespace.Prometheus.Config.V1.Rules;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Grafana.OpenApiClient.ConvertNamespace.Prometheus.Config.V1
{
    /// <summary>
    /// Builds and executes requests for operations under \convert\prometheus\config\v1
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class V1RequestBuilder : BaseRequestBuilder
    {
        /// <summary>The rules property</summary>
        public global::Soenneker.Grafana.OpenApiClient.ConvertNamespace.Prometheus.Config.V1.Rules.RulesRequestBuilder Rules
        {
            get => new global::Soenneker.Grafana.OpenApiClient.ConvertNamespace.Prometheus.Config.V1.Rules.RulesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Grafana.OpenApiClient.ConvertNamespace.Prometheus.Config.V1.V1RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V1RequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/convert/prometheus/config/v1", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Grafana.OpenApiClient.ConvertNamespace.Prometheus.Config.V1.V1RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V1RequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/convert/prometheus/config/v1", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
