// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Grafana.OpenApiClient.Admin.Ldap.Item;
using Soenneker.Grafana.OpenApiClient.Admin.Ldap.Reload;
using Soenneker.Grafana.OpenApiClient.Admin.Ldap.Status;
using Soenneker.Grafana.OpenApiClient.Admin.Ldap.Sync;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Grafana.OpenApiClient.Admin.Ldap
{
    /// <summary>
    /// Builds and executes requests for operations under \admin\ldap
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LdapRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The reload property</summary>
        public global::Soenneker.Grafana.OpenApiClient.Admin.Ldap.Reload.ReloadRequestBuilder Reload
        {
            get => new global::Soenneker.Grafana.OpenApiClient.Admin.Ldap.Reload.ReloadRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The status property</summary>
        public global::Soenneker.Grafana.OpenApiClient.Admin.Ldap.Status.StatusRequestBuilder Status
        {
            get => new global::Soenneker.Grafana.OpenApiClient.Admin.Ldap.Status.StatusRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The sync property</summary>
        public global::Soenneker.Grafana.OpenApiClient.Admin.Ldap.Sync.SyncRequestBuilder Sync
        {
            get => new global::Soenneker.Grafana.OpenApiClient.Admin.Ldap.Sync.SyncRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Soenneker.Grafana.OpenApiClient.admin.ldap.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Soenneker.Grafana.OpenApiClient.Admin.Ldap.Item.WithUser_nameItemRequestBuilder"/></returns>
        public global::Soenneker.Grafana.OpenApiClient.Admin.Ldap.Item.WithUser_nameItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("user_name", position);
                return new global::Soenneker.Grafana.OpenApiClient.Admin.Ldap.Item.WithUser_nameItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Grafana.OpenApiClient.Admin.Ldap.LdapRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LdapRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/admin/ldap", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Grafana.OpenApiClient.Admin.Ldap.LdapRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LdapRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/admin/ldap", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
