// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Grafana.OpenApiClient.Admin.Provisioning.Plugins.Reload;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Grafana.OpenApiClient.Admin.Provisioning.Plugins
{
    /// <summary>
    /// Builds and executes requests for operations under \admin\provisioning\plugins
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PluginsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The reload property</summary>
        public global::Soenneker.Grafana.OpenApiClient.Admin.Provisioning.Plugins.Reload.ReloadRequestBuilder Reload
        {
            get => new global::Soenneker.Grafana.OpenApiClient.Admin.Provisioning.Plugins.Reload.ReloadRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Grafana.OpenApiClient.Admin.Provisioning.Plugins.PluginsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PluginsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/admin/provisioning/plugins", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Grafana.OpenApiClient.Admin.Provisioning.Plugins.PluginsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PluginsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/admin/provisioning/plugins", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
