// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Serialization.Form;
using Microsoft.Kiota.Serialization.Json;
using Microsoft.Kiota.Serialization.Multipart;
using Microsoft.Kiota.Serialization.Text;
using Soenneker.Grafana.OpenApiClient.AccessControl;
using Soenneker.Grafana.OpenApiClient.Admin;
using Soenneker.Grafana.OpenApiClient.Annotations;
using Soenneker.Grafana.OpenApiClient.Anonymous;
using Soenneker.Grafana.OpenApiClient.Cloudmigration;
using Soenneker.Grafana.OpenApiClient.ConvertNamespace;
using Soenneker.Grafana.OpenApiClient.Dashboard;
using Soenneker.Grafana.OpenApiClient.Dashboards;
using Soenneker.Grafana.OpenApiClient.Datasources;
using Soenneker.Grafana.OpenApiClient.Ds;
using Soenneker.Grafana.OpenApiClient.Folders;
using Soenneker.Grafana.OpenApiClient.Groupsync;
using Soenneker.Grafana.OpenApiClient.Health;
using Soenneker.Grafana.OpenApiClient.LibraryElements;
using Soenneker.Grafana.OpenApiClient.Licensing;
using Soenneker.Grafana.OpenApiClient.Logout;
using Soenneker.Grafana.OpenApiClient.Org;
using Soenneker.Grafana.OpenApiClient.Orgs;
using Soenneker.Grafana.OpenApiClient.Playlists;
using Soenneker.Grafana.OpenApiClient.Public;
using Soenneker.Grafana.OpenApiClient.QueryHistory;
using Soenneker.Grafana.OpenApiClient.RecordingRules;
using Soenneker.Grafana.OpenApiClient.Reports;
using Soenneker.Grafana.OpenApiClient.Saml;
using Soenneker.Grafana.OpenApiClient.Search;
using Soenneker.Grafana.OpenApiClient.Serviceaccounts;
using Soenneker.Grafana.OpenApiClient.SigningKeys;
using Soenneker.Grafana.OpenApiClient.Snapshot;
using Soenneker.Grafana.OpenApiClient.Snapshots;
using Soenneker.Grafana.OpenApiClient.SnapshotsDelete;
using Soenneker.Grafana.OpenApiClient.Teams;
using Soenneker.Grafana.OpenApiClient.User;
using Soenneker.Grafana.OpenApiClient.Users;
using Soenneker.Grafana.OpenApiClient.V1;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Grafana.OpenApiClient
{
    /// <summary>
    /// The main entry point of the SDK, exposes the configuration and the fluent API.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GrafanaOpenApiClient : BaseRequestBuilder
    {
        /// <summary>The accessControl property</summary>
        public global::Soenneker.Grafana.OpenApiClient.AccessControl.AccessControlRequestBuilder AccessControl
        {
            get => new global::Soenneker.Grafana.OpenApiClient.AccessControl.AccessControlRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The admin property</summary>
        public global::Soenneker.Grafana.OpenApiClient.Admin.AdminRequestBuilder Admin
        {
            get => new global::Soenneker.Grafana.OpenApiClient.Admin.AdminRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The annotations property</summary>
        public global::Soenneker.Grafana.OpenApiClient.Annotations.AnnotationsRequestBuilder Annotations
        {
            get => new global::Soenneker.Grafana.OpenApiClient.Annotations.AnnotationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The anonymous property</summary>
        public global::Soenneker.Grafana.OpenApiClient.Anonymous.AnonymousRequestBuilder Anonymous
        {
            get => new global::Soenneker.Grafana.OpenApiClient.Anonymous.AnonymousRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The cloudmigration property</summary>
        public global::Soenneker.Grafana.OpenApiClient.Cloudmigration.CloudmigrationRequestBuilder Cloudmigration
        {
            get => new global::Soenneker.Grafana.OpenApiClient.Cloudmigration.CloudmigrationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The convert property</summary>
        public global::Soenneker.Grafana.OpenApiClient.ConvertNamespace.ConvertRequestBuilder Convert
        {
            get => new global::Soenneker.Grafana.OpenApiClient.ConvertNamespace.ConvertRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The dashboard property</summary>
        public global::Soenneker.Grafana.OpenApiClient.Dashboard.DashboardRequestBuilder Dashboard
        {
            get => new global::Soenneker.Grafana.OpenApiClient.Dashboard.DashboardRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The dashboards property</summary>
        public global::Soenneker.Grafana.OpenApiClient.Dashboards.DashboardsRequestBuilder Dashboards
        {
            get => new global::Soenneker.Grafana.OpenApiClient.Dashboards.DashboardsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The datasources property</summary>
        public global::Soenneker.Grafana.OpenApiClient.Datasources.DatasourcesRequestBuilder Datasources
        {
            get => new global::Soenneker.Grafana.OpenApiClient.Datasources.DatasourcesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ds property</summary>
        public global::Soenneker.Grafana.OpenApiClient.Ds.DsRequestBuilder Ds
        {
            get => new global::Soenneker.Grafana.OpenApiClient.Ds.DsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The folders property</summary>
        public global::Soenneker.Grafana.OpenApiClient.Folders.FoldersRequestBuilder Folders
        {
            get => new global::Soenneker.Grafana.OpenApiClient.Folders.FoldersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The groupsync property</summary>
        public global::Soenneker.Grafana.OpenApiClient.Groupsync.GroupsyncRequestBuilder Groupsync
        {
            get => new global::Soenneker.Grafana.OpenApiClient.Groupsync.GroupsyncRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The health property</summary>
        public global::Soenneker.Grafana.OpenApiClient.Health.HealthRequestBuilder Health
        {
            get => new global::Soenneker.Grafana.OpenApiClient.Health.HealthRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The libraryElements property</summary>
        public global::Soenneker.Grafana.OpenApiClient.LibraryElements.LibraryElementsRequestBuilder LibraryElements
        {
            get => new global::Soenneker.Grafana.OpenApiClient.LibraryElements.LibraryElementsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The licensing property</summary>
        public global::Soenneker.Grafana.OpenApiClient.Licensing.LicensingRequestBuilder Licensing
        {
            get => new global::Soenneker.Grafana.OpenApiClient.Licensing.LicensingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The logout property</summary>
        public global::Soenneker.Grafana.OpenApiClient.Logout.LogoutRequestBuilder Logout
        {
            get => new global::Soenneker.Grafana.OpenApiClient.Logout.LogoutRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The org property</summary>
        public global::Soenneker.Grafana.OpenApiClient.Org.OrgRequestBuilder Org
        {
            get => new global::Soenneker.Grafana.OpenApiClient.Org.OrgRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The orgs property</summary>
        public global::Soenneker.Grafana.OpenApiClient.Orgs.OrgsRequestBuilder Orgs
        {
            get => new global::Soenneker.Grafana.OpenApiClient.Orgs.OrgsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The playlists property</summary>
        public global::Soenneker.Grafana.OpenApiClient.Playlists.PlaylistsRequestBuilder Playlists
        {
            get => new global::Soenneker.Grafana.OpenApiClient.Playlists.PlaylistsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The public property</summary>
        public global::Soenneker.Grafana.OpenApiClient.Public.PublicRequestBuilder Public
        {
            get => new global::Soenneker.Grafana.OpenApiClient.Public.PublicRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The queryHistory property</summary>
        public global::Soenneker.Grafana.OpenApiClient.QueryHistory.QueryHistoryRequestBuilder QueryHistory
        {
            get => new global::Soenneker.Grafana.OpenApiClient.QueryHistory.QueryHistoryRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The recordingRules property</summary>
        public global::Soenneker.Grafana.OpenApiClient.RecordingRules.RecordingRulesRequestBuilder RecordingRules
        {
            get => new global::Soenneker.Grafana.OpenApiClient.RecordingRules.RecordingRulesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The reports property</summary>
        public global::Soenneker.Grafana.OpenApiClient.Reports.ReportsRequestBuilder Reports
        {
            get => new global::Soenneker.Grafana.OpenApiClient.Reports.ReportsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The saml property</summary>
        public global::Soenneker.Grafana.OpenApiClient.Saml.SamlRequestBuilder Saml
        {
            get => new global::Soenneker.Grafana.OpenApiClient.Saml.SamlRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The search property</summary>
        public global::Soenneker.Grafana.OpenApiClient.Search.SearchRequestBuilder Search
        {
            get => new global::Soenneker.Grafana.OpenApiClient.Search.SearchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The serviceaccounts property</summary>
        public global::Soenneker.Grafana.OpenApiClient.Serviceaccounts.ServiceaccountsRequestBuilder Serviceaccounts
        {
            get => new global::Soenneker.Grafana.OpenApiClient.Serviceaccounts.ServiceaccountsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The signingKeys property</summary>
        public global::Soenneker.Grafana.OpenApiClient.SigningKeys.SigningKeysRequestBuilder SigningKeys
        {
            get => new global::Soenneker.Grafana.OpenApiClient.SigningKeys.SigningKeysRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The snapshot property</summary>
        public global::Soenneker.Grafana.OpenApiClient.Snapshot.SnapshotRequestBuilder Snapshot
        {
            get => new global::Soenneker.Grafana.OpenApiClient.Snapshot.SnapshotRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The snapshots property</summary>
        public global::Soenneker.Grafana.OpenApiClient.Snapshots.SnapshotsRequestBuilder Snapshots
        {
            get => new global::Soenneker.Grafana.OpenApiClient.Snapshots.SnapshotsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The snapshotsDelete property</summary>
        public global::Soenneker.Grafana.OpenApiClient.SnapshotsDelete.SnapshotsDeleteRequestBuilder SnapshotsDelete
        {
            get => new global::Soenneker.Grafana.OpenApiClient.SnapshotsDelete.SnapshotsDeleteRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The teams property</summary>
        public global::Soenneker.Grafana.OpenApiClient.Teams.TeamsRequestBuilder Teams
        {
            get => new global::Soenneker.Grafana.OpenApiClient.Teams.TeamsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The user property</summary>
        public global::Soenneker.Grafana.OpenApiClient.User.UserRequestBuilder User
        {
            get => new global::Soenneker.Grafana.OpenApiClient.User.UserRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The users property</summary>
        public global::Soenneker.Grafana.OpenApiClient.Users.UsersRequestBuilder Users
        {
            get => new global::Soenneker.Grafana.OpenApiClient.Users.UsersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The v1 property</summary>
        public global::Soenneker.Grafana.OpenApiClient.V1.V1RequestBuilder V1
        {
            get => new global::Soenneker.Grafana.OpenApiClient.V1.V1RequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Grafana.OpenApiClient.GrafanaOpenApiClient"/> and sets the default values.
        /// </summary>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GrafanaOpenApiClient(IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}", new Dictionary<string, object>())
        {
            ApiClientBuilder.RegisterDefaultSerializer<JsonSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<TextSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<FormSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<MultipartSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<TextParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<FormParseNodeFactory>();
            if (string.IsNullOrEmpty(RequestAdapter.BaseUrl))
            {
                RequestAdapter.BaseUrl = "/api";
            }
            PathParameters.TryAdd("baseurl", RequestAdapter.BaseUrl);
        }
    }
}
#pragma warning restore CS0618
