// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Grafana.OpenApiClient.V1.Provisioning.AlertRules.Export
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetFormatQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "yaml")]
        #pragma warning disable CS1591
        Yaml,
        #pragma warning restore CS1591
        [EnumMember(Value = "json")]
        #pragma warning disable CS1591
        Json,
        #pragma warning restore CS1591
        [EnumMember(Value = "hcl")]
        #pragma warning disable CS1591
        Hcl,
        #pragma warning restore CS1591
    }
}
