// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Grafana.OpenApiClient.LibraryElements.Item;
using Soenneker.Grafana.OpenApiClient.LibraryElements.Name;
using Soenneker.Grafana.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Grafana.OpenApiClient.LibraryElements
{
    /// <summary>
    /// Builds and executes requests for operations under \library-elements
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LibraryElementsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The name property</summary>
        public global::Soenneker.Grafana.OpenApiClient.LibraryElements.Name.NameRequestBuilder Name
        {
            get => new global::Soenneker.Grafana.OpenApiClient.LibraryElements.Name.NameRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Soenneker.Grafana.OpenApiClient.libraryElements.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Soenneker.Grafana.OpenApiClient.LibraryElements.Item.WithLibrary_element_uItemRequestBuilder"/></returns>
        public global::Soenneker.Grafana.OpenApiClient.LibraryElements.Item.WithLibrary_element_uItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("library_element_uid", position);
                return new global::Soenneker.Grafana.OpenApiClient.LibraryElements.Item.WithLibrary_element_uItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Grafana.OpenApiClient.LibraryElements.LibraryElementsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LibraryElementsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/library-elements{?excludeUid*,folderFilter*,folderFilterUIDs*,kind*,page*,perPage*,searchString*,sortDirection*,typeFilter*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Grafana.OpenApiClient.LibraryElements.LibraryElementsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LibraryElementsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/library-elements{?excludeUid*,folderFilter*,folderFilterUIDs*,kind*,page*,perPage*,searchString*,sortDirection*,typeFilter*}", rawUrl)
        {
        }
        /// <summary>
        /// Returns a list of all library elements the authenticated user has permission to view.Use the `perPage` query parameter to control the maximum number of library elements returned; the default limit is `100`.You can also use the `page` query parameter to fetch library elements from any page other than the first one.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Grafana.OpenApiClient.Models.LibraryElementSearchResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Grafana.OpenApiClient.Models.ErrorResponseBody">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Grafana.OpenApiClient.Models.ErrorResponseBody">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Grafana.OpenApiClient.Models.LibraryElementSearchResponse?> GetAsync(Action<RequestConfiguration<global::Soenneker.Grafana.OpenApiClient.LibraryElements.LibraryElementsRequestBuilder.LibraryElementsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Grafana.OpenApiClient.Models.LibraryElementSearchResponse> GetAsync(Action<RequestConfiguration<global::Soenneker.Grafana.OpenApiClient.LibraryElements.LibraryElementsRequestBuilder.LibraryElementsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::Soenneker.Grafana.OpenApiClient.Models.ErrorResponseBody.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Grafana.OpenApiClient.Models.ErrorResponseBody.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Grafana.OpenApiClient.Models.LibraryElementSearchResponse>(requestInfo, global::Soenneker.Grafana.OpenApiClient.Models.LibraryElementSearchResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Creates a new library element.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Grafana.OpenApiClient.Models.LibraryElementResponse"/></returns>
        /// <param name="body">CreateLibraryElementCommand is the command for adding a LibraryElement</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Grafana.OpenApiClient.Models.ErrorResponseBody">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Grafana.OpenApiClient.Models.ErrorResponseBody">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Grafana.OpenApiClient.Models.ErrorResponseBody">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Grafana.OpenApiClient.Models.ErrorResponseBody">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Grafana.OpenApiClient.Models.ErrorResponseBody">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Grafana.OpenApiClient.Models.LibraryElementResponse?> PostAsync(global::Soenneker.Grafana.OpenApiClient.Models.CreateLibraryElementCommand body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Grafana.OpenApiClient.Models.LibraryElementResponse> PostAsync(global::Soenneker.Grafana.OpenApiClient.Models.CreateLibraryElementCommand body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Grafana.OpenApiClient.Models.ErrorResponseBody.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Grafana.OpenApiClient.Models.ErrorResponseBody.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Grafana.OpenApiClient.Models.ErrorResponseBody.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Grafana.OpenApiClient.Models.ErrorResponseBody.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Grafana.OpenApiClient.Models.ErrorResponseBody.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Grafana.OpenApiClient.Models.LibraryElementResponse>(requestInfo, global::Soenneker.Grafana.OpenApiClient.Models.LibraryElementResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns a list of all library elements the authenticated user has permission to view.Use the `perPage` query parameter to control the maximum number of library elements returned; the default limit is `100`.You can also use the `page` query parameter to fetch library elements from any page other than the first one.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Grafana.OpenApiClient.LibraryElements.LibraryElementsRequestBuilder.LibraryElementsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Grafana.OpenApiClient.LibraryElements.LibraryElementsRequestBuilder.LibraryElementsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Creates a new library element.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">CreateLibraryElementCommand is the command for adding a LibraryElement</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Grafana.OpenApiClient.Models.CreateLibraryElementCommand body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Grafana.OpenApiClient.Models.CreateLibraryElementCommand body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Grafana.OpenApiClient.LibraryElements.LibraryElementsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Grafana.OpenApiClient.LibraryElements.LibraryElementsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Grafana.OpenApiClient.LibraryElements.LibraryElementsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Returns a list of all library elements the authenticated user has permission to view.Use the `perPage` query parameter to control the maximum number of library elements returned; the default limit is `100`.You can also use the `page` query parameter to fetch library elements from any page other than the first one.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class LibraryElementsRequestBuilderGetQueryParameters 
        {
            /// <summary>Element UID to exclude from search results.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("excludeUid")]
            public string? ExcludeUid { get; set; }
#nullable restore
#else
            [QueryParameter("excludeUid")]
            public string ExcludeUid { get; set; }
#endif
            /// <summary>A comma separated list of folder ID(s) to filter the elements by.Deprecated: Use FolderFilterUIDs instead.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("folderFilter")]
            public string? FolderFilter { get; set; }
#nullable restore
#else
            [QueryParameter("folderFilter")]
            public string FolderFilter { get; set; }
#endif
            /// <summary>A comma separated list of folder UID(s) to filter the elements by.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("folderFilterUIDs")]
            public string? FolderFilterUIDs { get; set; }
#nullable restore
#else
            [QueryParameter("folderFilterUIDs")]
            public string FolderFilterUIDs { get; set; }
#endif
            /// <summary>Kind of element to search for.</summary>
            [QueryParameter("kind")]
            public long? Kind { get; set; }
            /// <summary>The page for a set of records, given that only perPage records are returned at a time. Numbering starts at 1.</summary>
            [QueryParameter("page")]
            public long? Page { get; set; }
            /// <summary>The number of results per page.</summary>
            [QueryParameter("perPage")]
            public long? PerPage { get; set; }
            /// <summary>Part of the name or description searched for.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("searchString")]
            public string? SearchString { get; set; }
#nullable restore
#else
            [QueryParameter("searchString")]
            public string SearchString { get; set; }
#endif
            /// <summary>Sort order of elements.</summary>
            [QueryParameter("sortDirection")]
            public global::Soenneker.Grafana.OpenApiClient.LibraryElements.GetSortDirectionQueryParameterType? SortDirection { get; set; }
            /// <summary>A comma separated list of types to filter the elements by</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("typeFilter")]
            public string? TypeFilter { get; set; }
#nullable restore
#else
            [QueryParameter("typeFilter")]
            public string TypeFilter { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
