// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Grafana.OpenApiClient.Licensing.Check;
using Soenneker.Grafana.OpenApiClient.Licensing.CustomPermissions;
using Soenneker.Grafana.OpenApiClient.Licensing.CustomPermissionsCsv;
using Soenneker.Grafana.OpenApiClient.Licensing.RefreshStats;
using Soenneker.Grafana.OpenApiClient.Licensing.Token;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Grafana.OpenApiClient.Licensing
{
    /// <summary>
    /// Builds and executes requests for operations under \licensing
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LicensingRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The check property</summary>
        public global::Soenneker.Grafana.OpenApiClient.Licensing.Check.CheckRequestBuilder Check
        {
            get => new global::Soenneker.Grafana.OpenApiClient.Licensing.Check.CheckRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The customPermissions property</summary>
        public global::Soenneker.Grafana.OpenApiClient.Licensing.CustomPermissions.CustomPermissionsRequestBuilder CustomPermissions
        {
            get => new global::Soenneker.Grafana.OpenApiClient.Licensing.CustomPermissions.CustomPermissionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The customPermissionsCsv property</summary>
        public global::Soenneker.Grafana.OpenApiClient.Licensing.CustomPermissionsCsv.CustomPermissionsCsvRequestBuilder CustomPermissionsCsv
        {
            get => new global::Soenneker.Grafana.OpenApiClient.Licensing.CustomPermissionsCsv.CustomPermissionsCsvRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The refreshStats property</summary>
        public global::Soenneker.Grafana.OpenApiClient.Licensing.RefreshStats.RefreshStatsRequestBuilder RefreshStats
        {
            get => new global::Soenneker.Grafana.OpenApiClient.Licensing.RefreshStats.RefreshStatsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The token property</summary>
        public global::Soenneker.Grafana.OpenApiClient.Licensing.Token.TokenRequestBuilder Token
        {
            get => new global::Soenneker.Grafana.OpenApiClient.Licensing.Token.TokenRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Grafana.OpenApiClient.Licensing.LicensingRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LicensingRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/licensing", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Grafana.OpenApiClient.Licensing.LicensingRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LicensingRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/licensing", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
